_config.yml
Fixes the issue first noted in #5.
=> jekyll: ignore erc-template.md

ERCS/erc-5164.md
Originally here: https://github.com/ethereum/EIPs/pull/7911
Moves ERC-5164 to Last Call
The spec has seen a number of implementations, and is stable.
- PoolTogether 5164 wrappers for [Optimism, Arbitrum and Polygon](https://github.com/pooltogether/erc5164)
- [Hyperlane has implemented ERC-5164](https://docs.hyperlane.xyz/docs/apis-and-sdks/hooks#erc-5164-hook)
- [Multi-bridge Message Aggregator](https://multi-message-aggregation.gitbook.io/multi-message-aggregation/start-here/multi-bridge-message-aggregation) that originated from the Uniswap Forums.
- Hop Protocol has committed to using the standard
Additionally we have endorsement from Uniswap:
- Uniswap Bridge Report [recommendations](https://uniswap.notion.site/Bridge-Assessment-Report-0c8477afadce425abac9c0bd175ca382) were to lean …
=> Updated 5164 to Last Call

ERCS/erc-5189.md
Formatting updates. 
Updates as per latest discussion. 
Description updates. 
Moved from https://github.com/ethereum/EIPs/pull/7854
=> ERC-5189 updates

ERCS/erc-7254.md
Per #8, we're still using `eip` in links because of the joint build occurring in `ethereum/EIPs`.
=> Update ERC-7254: fix broken links

ERCS/erc-6982.md
This clarifies the description of the DefaultLocked event, to make it clear that the emission of a new DefaultLocked event establishes the default behavior of all the tokens, including the ones already minted.
It also fixes an error referring to Cruna protocol, where protectors where mistakenly called initiators.
=> Update ERC-6982: Clarifying description

ERCS/erc-223.md
Migration from https://github.com/ethereum/EIPs/pull/7856
=> Update ERC-223: Remove `standard` function

ERCS/erc-6900.md
This change was introduced in the latest spec update, but the function was accidentally left out of the `IPlugin` interface. The struct has already been added, so just adding in the function in the interface here.
=> Update ERC-6900: Add missing `pluginMetadata()` method

ERCS/erc-6900.md
This was missed in a prior spec update.
=> Update ERC-6900: Fix incorrect `dependencies` type in `installPlugin`

ERCS/erc-5216.md, assets/erc-5216/ERC5216.sol
Hey,
I'm updating this ERC due to a several reasons:
- Rename all "EIP" for "ERC".
- Change internal links to continue working with the new repository structure.
- Rename the title from "ERC-1155 Approval by Amount Extension" to "ERC-1155 Allowance Extension", suggested by https://ethereum-magicians.org/t/last-call-eip-5216-erc1155-approval-by-amount/9898/9 with the approval of both creators.
-  Changed and updated Solidity code to keep it simple and working.
In addition, I would like to pose a question to the editors and maintainers. Given the deadline date, what about the status of this ERC? Still in last call?
Thanks in advance
=> Update ERC-5216: ERC-5216 global update

ERCS/erc-7590.md, ERCS/erc20-holder-extension-for-nfts.md, assets/erc-7590/contracts/AbstractERC7590.sol, assets/erc-7590/contracts/ERC20Mock.sol, assets/erc-7590/contracts/ERC7590Mock.sol, assets/erc-7590/contracts/IERC7590.sol, assets/erc-7590/hardhat.config.ts, assets/erc-7590/package.json, assets/erc-7590/test/erc7590.ts
=> Add ERC: ERC-20 Holder Extension for NFTs

ERCS/erc-7572.md, ERCS/erc-xxxx.md
Discussion: https://ethereum-magicians.org/t/erc-contract-level-metadata-via-contracturi/17157
=> Add ERC: Contract-level metadata via `contractURI()`

ERCS/erc-5564.md, assets/erc-5564/scheme_ids.md
- Update the scheme ID for the SECP256k1 implementation from 0 to 1.
- Add content to the implementation section
=> Update ERC-5564: update schemeID

ERCS/erc-7092.md
=> Update ERC-7092: Move to Last Call

ERCS/erc-5189.md
It adds two additional features to the ERC:
- `block.basefee` scaling factor, it allows the bundler and the endorser to agree on a common exchange rate for the `block.basefee`; avoiding the need to infer it from 3rd sources.
- Untrusted environments, it allows the endorser to add unknown execution paths into the list of dependencies.
=> Update ERC-5189: ERC5189 - Scaling factor and untrusted environments

ERCS/erc-7425.md
Add a security consideration and improve specification language  for clarity.
=> Update ERC-7425: Add missing info

ERCS/erc-1363.md
Just adding an explicit return value docs as it was missing for no reason.
The `approveAndCall` methods are aligned with the `transferAndCall` and `transferFromAndCall` methods.
=> Update ERC-1363: Add missing return statement

ERCS/erc-5573.md
Fixes some details:
- Missing trailing slashes in some URIs; test cases didn't match
- Duplicate `:` in ReCaps URI spec
- Javascript -> JavaScript
- Misspelling of receive
=> Update ERC-5573: ERC-5573 typos

ERCS/erc-5189.md
- Use the `Operation` struct for `isOperationReady`, leads to cleaner endorsers
- Apply fee scaling at the end of the fee formula
- Add `fixedGas`
=> Update ERC-5189: ERC5189 Structure and Fee changes

ERCS/erc-777.md
=> Update ERC-777: fix typo

ERCS/erc-7531.md
A problem in the original proposal is that there can be multiple types of rights. One is the ownership, but not less important is the right to use an NFT (for example to play a game or participate in a DAO). Adding a parameter to take care of it is a better way to manage it without blocking future evolutions. 
The idea is to use a bytes4 parameter to identify the kind of right. The initial rights suggested by the interface are `ownership` and `usage`. They are supposed to be encoded as 
```
bytes4(keccak256(right));
```
So that we have 
- `0x399d2b36`   `// bytes4(keccak256("ownership"))`
- `0x230a5961`   `// bytes4(keccak256("usage"))`
=> Update ERC-7531: Adding rights to ERC7531

ERCS/erc-7508.md, assets/erc-7508/contracts/AttributesRepository.sol, assets/erc-7508/contracts/IERC7508.sol, assets/erc-7508/test/attributesRepository.ts
- Renames Issuer for Owner in token attributes.
- Renames methods to set and get collection attributes metadata to make it explicit they are per collection. Adds full test coverage for token attributes.
- Sorts methods on RMRKTokenAttributesRepository.
- Updates interfaceId.
=> Update ERC-7508: Improvements on ERC7508.

ERCS/erc-7598.md, ERCS/erc-TBD-twa.md
From developers at [circlefin](https://github.com/circlefin), we are proposing a new extension for ERC-3009 Transfer with Authorization, which has already been added to USDC v2.2.
Discussion thread: https://ethereum-magicians.org/t/add-erc-contract-signature-validation-extension-for-erc-3009-transfer-with-authorization/18158
=> Add ERC: Use contract signature for signed transfer

ERCS/erc-6538.md, assets/erc-6538/contracts/ERC6538Registry.sol, assets/erc-6538/contracts/interfaces/IERC6538Registry.sol
=> Update ERC-6538: Move to Review

ERCS/erc-7531.md
Fixing a typo @param right (it was rights, which was wrong)
=> Update ERC-7531: Fix typo in IERC7531

ERCS/erc-7531.md
This fixes a typo and remove restrictions that where mistakenly set.
=> Update ERC-7531: Fix typo and remove unnecessary specifications

ERCS/erc-5564.md, assets/erc-5564/contracts/ERC5564Announcer.sol, assets/erc-5564/contracts/interfaces/IERC5564Announcer.sol, assets/erc-5564/scheme_ids.md
=> Update ERC-5564: Move to Last Call

ERCS/erc-7399.md
Noticed that there is no specification around `maxFlashLoan`, so I added one consistent to the current implementation of the wrappers at https://github.com/alcueca/erc7399-wrappers
=> Update ERC-7399: Provided clarity around `maxFlashLoan`

ERCS/erc-7201.md
This PR fixes one formula in the ERC7201, I am not one of the authors
=> Update ERC-7201: Fix solidity formula

ERCS/erc-7580.md, ERCS/erc-xxxx.md
=> Add ERC: Advertisement Tracking Interface

ERCS/erc-5189.md, ERCS/erc-6900.md
After speaking with other developers about ERC-7432, we reach the conclusion that the interface is becoming overly complex by attempting to support multiple use cases.
We are simplifying this EIP by removing the non-unique roles use case.
=> Update ERC-7432: Removed non-unique roles

ERCS/erc-2135.md, ERCS/erc-2615.md, ERCS/erc-4527.md, ERCS/erc-5023.md, ERCS/erc-5252.md, ERCS/erc-5521.md, ERCS/erc-6105.md, ERCS/erc-6120.md
=> Update ERC-2135: fix some typos

ERCS/erc-7656.md
Renaming the token linked contract interface from the too generic `IERC7656Contract` to `IERC7656Linked`
=> Update ERC-7656: Rename IERC7656Contract as IER7656Linked

ERCS/erc-4337.md
The value of postOpGasLimit can't be reliably estimated: the paymaster depends on this value, and can't trust the account to estimate a proper value, so it must require a fixed, known value.
=> Update ERC-4337: return values of estimateUserOperationGas

assets/erc-6220/contracts/utils/EquipRenderUtils.sol
EIP-6220: EquipRenderUtils.sol Import Path Fix
This pull request introduces a fix for the import path issue in EquipRenderUtils.sol related to the ERC-6220 standard. Previously, the file incorrectly imported IEquippable.sol, a file that does not exist in the current directory structure. This has been corrected to import IERC6220.sol, aligning with the intended interface usage and resolving the build error HH404.
Changes Made:
Modified import statements in EquipRenderUtils.sol from ../IEquippable.sol to ../IERC6220.sol.
Updated interface references from IEquippable to IERC6220 within EquipRenderUtils.sol to reflect the correct interface.
Justification:
This change is crucial for the successful compilation and execution of the ERC-6220 standard contracts. It ensures that the correct …
=> Update ERC-6220: fix Import path in EquipRenderUtils.sol

ERCS/erc-7682.md, ERCS/erc-draft_auxiliary-funds.md
Defines an EIP-5792 compliant capability that allows wallets to indicate to apps that they have access to funds beyond those that can be accounted for by looking up balances onchain given the wallet's address.
https://ethereum-magicians.org/t/add-erc-auxiliary-funds-capability/19599
=> Add ERC: Auxiliary Funds Capability

ERCS/erc-1046.md
=> Update ERC-1046: fixing typos #297

ERCS/erc-6909.md
ohhh i'm gonna `[Informational - 1]`
=> Update ERC-6909: Nit, adds case to `transferFrom` where `sender` is `msg.sender`.

ERCS/erc-7015.md
I'm requesting that we move ERC-7015 to Review and Last Call soon. I've checked in with the key stakeholders (Zora and OS), and they implemented and are happy with the current state of the ERC.
=> Update ERC-7015: Move to Review

ERCS/erc-6900.md
- Corrected "Responsibilties" to "Responsibilities".
=> Update ERC-6900: Fix typo in responsibilities section

ERCS/erc-838.md
This PR includes the missing ERC838
It was firstly described here: https://github.com/ethereum/EIPs/issues/838
I am not one of the original authors
the first inclusion attempt hapnned here: https://github.com/ethereum/EIPs/pull/7186
and later it was recommended to be made here,
Solidity already implements this
=> Add ERC: ABI specification for REVERT reason string

ERCS/erc-3770.md
we should revive this one (especially as it is used and currently pushed by @vbuterin here: https://x.com/VitalikButerin/status/1810633473750683974)
So moving it from stagnant to draft.
Also removing the responsibility on Ethereum-Lists curators (currently only me) to care for similar looking names. This is just not possible. It is just a drawback of this EIP in contrast of CAIP-10.
=> Update ERC-3770: Move to Draft

ERCS/erc-5630.md
The EIP was moved to Stagnant state automatically, but there are many applications waiting for a replacement to the now deprecated support for eth_getEncryptionPublicKey   .  
Authors: J.D. Bertron <jdbertron>
=> Update ERC-5630: Move to Draft

ERCS/erc-7682.md
- change `auxiliaryFunds` from a single boolean to an array of supported assets
=> Update ERC-7682: Add assets

ERCS/erc-7677.md
Community is aligned here, and API has a good amount of usage in the ecosystem. A move to last call will follow, thought this was already in review.
=> Update ERC-7677: Move to Review

ERCS/erc-7677.md
moves ERC-7677 to last call with deadline 9/5/2024
=> Update ERC-7677: Move to Last Call

ERCS/erc-3770.md
Fixes broken links from the eip -> erc move, fixes typos and formatting
=> Update ERC-3770: Fix broken links and formatting

ERCS/erc-7677.md
- specified that paymaster service must return postOpGasLimit for EntryPoint v0.7, as the paymaster pays this and should not trust the account to estimate it.
=> Update ERC-7677: postopgas callout

ERCS/erc-7432.md
After a few months iterating and gathering feedback, we are proposing to move ERC-7432 to last call.
We are also including a proposed deadline of September 17th, but happy to adjust it as per the EIP Editors feedback.
=> Update ERC-7432: Move to Last Call

ERCS/erc-7656.md
In some of the interfaces it was used the word `account` instead of the more generic `service`. The wording has been fixed. Also, the interfaceId of `IERC7656Service` has been specified.
=> Update ERC-7656: Fix wording, using service instead of account, when needed

_includes/head.html
The `polyfill.io` domain was taken over by a malicious actor, and now injects code that redirects to unrelated websites.
References:
<https://sansec.io/research/polyfill-supply-chain-attack>
<https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet/>
=> Website: Remove polyfill.

ERCS/erc-7280.md, assets/erc-7280/samples/data/gtim1.json, assets/erc-7280/samples/data/music1.json, assets/erc-7280/samples/data/video1.json, assets/erc-7280/samples/schemas/GoogleTravelImpactModel.json, assets/erc-7280/samples/schemas/MusicRecording.json, assets/erc-7280/samples/schemas/VideoObject.json
=> Add ERC: NFT Metadata Extension like JSON-LD

ERCS/erc-6909.md
Minor updates to wording and removal of specification language from non-specification sections.
=> Update ERC-6909: Non-specification Nits

ERCS/erc-6734.md
=> Update ERC-6734: Move to Review

ERCS/erc-7579.md
Introducing two changes to ERC-7579
**Motivation:** what ERC7579 started with, was the need for the validator to always know where is what in the callData.
Validators need this knowledge to parse data about the execution and use it to validate/not validate a given userOp.
So 7579 proposed standard execution interface for the compliant SA: `execute(bytes32 mode, bytes calldata executionCalldata) method`
However, with `executeUserOp` this is not the case anymore.
With a standard execution flow, we know that the `EP` will call `SA` with `userOp.callData`
When `EP` calls `executeUserOp` , the `executeUserOp` implementation is free to use any part of the userOp.callData for the actual execution
Thus, with the `executeUserOp` flow, the module can never know for sure, where in the …
=> Update ERC-7579: executeUserOp + multitype module onInstall/onUninstall

_config.yml
Meta tags are currently broken in the site. For example:
```html
<link rel="canonical" href="https://eips.ethereum.org/ERCS/erc-7739" />
<meta property="og:url" content="https://eips.ethereum.org/ERCS/erc-7739" />
```
=> Fix site URL in Jekyll config

ERCS/erc-6909.md
- moved `eip` to `erc` where relevant
- added explicit requirement for ERC-165 implementation
- change metadata method descriptions (`name`/`symbol`) to say "_ for a token `id`" rather than "_ of the contract"
- added backticks where relevant
=> Update ERC-6909: ERC-6909 nits

ERCS/erc-5625.md
=> Update ERC-5625: Move to Last Call

ERCS/erc-7739.md, assets/erc-7739/contracts/accounts/ERC1271.sol
=> Update ERC-7739: Update ERC-7739

ERCS/eip-send-tx-conditional.md, ERCS/erc-7796.md
=> Add ERC: Conditional send transaction RPC

ERCS/erc-7683.md
This PR proposes a few updates to ERC-7683. These updates are intended to make the language and functionality in the ERC capture more use cases than originally foreseen, require less (or no) protocol-specific code and casework for fillers, and provide visibility into the opaque bytes fields used in the standard.
See this [PR](https://github.com/across-protocol/ERCs/pull/1) for wider discussion of these changes.
Notable changes:
1. Terminology: initiate is now called open. swap has been replaced with transfer throughout.
1. The ERC now standardizes the fill function and process (i.e. the function on the destination chain).
1. Because protocols may require information or state from the origin transaction (open), the standard now requires that the resolved order includes FillInstructions, …
=> Update ERC-7683: Extending the standard

ERCS/erc-3668.md
fixing ~4 years old typo 😆 
https://discuss.ens.domains/t/erc-3668-edge-case-for-clientside-http-ssl-errors/19617/2?u=0xc0de4c0ffee
cc @Arachnid 🙏
=> Update ERC-3668: fix typo in erc3668 lookup process

ERCS/erc-7761.md, ERCS/erc-7774.md
In the context of the [ERC-6860](./eip-6860.md) `web3://` standard, this ERC extends the [ERC-6944](./eip-6944.md) resolve mode: This standard add mechanisms to alleviate limitations to the use of standard [RFC 9111](https://www.rfc-editor.org/rfc/rfc9111) HTTP caching.
=> Add ERC: Cache invalidation in ERC-5219 mode Web3 URL

ERCS/erc-7821.md
The ERC refers to `supportsExecutionMode` as returning a boolean:
> Only returns true for:
And the reference implementation returns a boolean. Yet the interface specify returning a uint256. This looks like a mistake.
=> Update ERC-7821: Fix return type of `supportsExecutionMode` in interface definition.

ERCS/erc-7579.md
Multiple ERC7579 implementatins skip the ERC-165 interface and seems to not bee too much consensus around providing a usage for it. Other ERC-4337 related standards have implemented their detection mechanisms (e.g. see ERC-7739's detection) without relying on ERC-165.
Also, since the `IExecution` interface is not specified as `payable` but some accounts have implemented it this way, I'm adding comments to improve clarity.
=> Update ERC-7579: Make ERC165 optional and clarify payable execution

ERCS/erc-6860.md
This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `overriden` to `overridden`
Corrected `determing` to `determining`
Please review the changes and let me know if any additional changes are needed.
=> Update ERC-6860: typos

ERCS/erc-7744.md, ERCS/erc-7746.md, assets/erc-7744/CodeIndex.sol, assets/erc-7744/ICodeIndex.sol
This PR concludes discussion that was facilitated on the Magician forums, particularly: 
- Addresses self-destruct concerns
- Addresses EIP7702 delegated address concern 
- Changes solidity file names according to standard number 
- Changes salt and deployment address to accommodate bytecode changes
- New artifact was compiled with no metadata included to avoid bytecode changes if somone tries to re-compile it locally
=> Update ERC-7744: Move to Review

ERCS/erc-7528.md
The required EIP is actually ERC-55: Mixed-case checksum address encoding, not EIP-155: Simple replay attack protection
Source: https://eips.ethereum.org/EIPS/eip-55, https://eips.ethereum.org/EIPS/eip-155
=> Update ERC-7528: update required EIP for ETH (Native Asset) Address Convention

ERCS/erc-4883.md
Remove ERC165 requirement for compatibility with earlier SVG NFTs
=> Update ERC-4883: Update erc-4883.md

ERCS/erc-3668.md
Updates the label in the graph of erc 3668 to use the correct error code as defined a few lines below
=> Update ERC-3668: Update typo in erc-3668.md

ERCS/erc-7579.md
ERC-7579 defines multiples interfaces (`IExecution`, `IModule`, ...), some of which may clash with different interfaces defined in other ERCs. For example, both ERC-6900 and ERC-7579 define a `IModule` interfaces (and they are not compatibles).
Prefixing all interfaces declared in ERC-7579 with the name of the ERC avoid that kind of conflict. 
This is common practice: for example, ERC-721 and ERC-1155 defined `ERC721TokenReceiver` and `ERC1155TokenReceiver` respectivelly.
[A similar PR is targetting erc-6900.md with similar changes](https://github.com/ethereum/ERCs/pull/875)
=> Update ERC-7579: Prefix ERC-7579 interfaces names to avoid conflicts

_includes/head.html, assets/erc-2535/reference/Diamond.sol, assets/erc-2535/storage-examples/AppStorage.sol
"propery" - "property" 
"funciton" - "function" 
"regualar" - "regular" 
While these typos don't affect code functionality, fixing them:
- Improves documentation clarity
- Follows coding best practices
- Makes codebase more maintainable
I hope my corrections will help you. Thank you for your work.
=> Website: Fix typos and spelling errors in documentation

assets/erc-4675/contracts/interface/IERC721.sol, assets/erc-5247/ProposalRegistry.sol
changed:
tokenaId - tokenId
runnalbe - runnable
=> Fixing Typographical Errors in Documentation

ERCS/erc-1056.md
fix and update some minor typos.
there are some minor typos which fixed.
=> Update ERC-1056: Update erc-1056.md

ERCS/erc-6900.md
ERC-6900 defines multiples interfaces (`IModularAccount`, `IModule`, ...), some of which may clash with different interfaces defined in other ERCs. For example, both ERC-6900 and ERC-7579 define a `IModule` interfaces (and they are not compatibles).
Prefixing all interfaces declared in ERC-6900 with the name of the ERC avoid that kind of conflict. 
This is common practice: for example, ERC-721 and ERC-1155 defined `ERC721TokenReceiver` and `ERC1155TokenReceiver` respectivelly.
[A similar PR is targetting erc-7579.md with similar changes](https://github.com/ethereum/ERCs/pull/876)
=> Update ERC-6900: Prefix ERC-6900 interfaces names to avoid conflicts

ERCS/erc-7811.md, ERCS/erc-wallet-asset-discovery.md
JSON-RPC method for wallets to share a user’s complete asset list with Dapps, including assets not easily discoverable through on-chain information alone.
=> Add ERC: Wallet Asset Discovery

ERCS/erc-6220.md, assets/erc-6220/contracts/Catalog.sol, assets/erc-6220/contracts/EquippableToken.sol, assets/erc-6220/contracts/IERC6220.sol, assets/erc-6220/contracts/utils/EquipRenderUtils.sol, assets/erc-6220/test/multiasset.ts, assets/erc-6220/test/nestable.ts
=> Update ERC-6220: fix some typos

.github/workflows/jekyll.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
=> CI: bump actions/checkout to v4

ERCS/erc-7631.md
The implementations in the wild do not have any request for changes for more than a year, so moving to last call.
=> Update ERC-7631: Move to Last Call

ERCS/erc-3009.md, ERCS/erc-721.md, assets/erc-3009/EIP2612.sol, assets/erc-3009/EIP3009.sol, assets/erc-3009/LICENSE, assets/erc-721/LICENSE, assets/erc-721/SafeERC20.sol
Hi! I noticed a couple of broken links while reading through the EIP docs:
- In `ERC-3009.md`, there was a sneaky typo in the `EIP-2612` implementation link — `EI32612.sol` instead of `EIP2612.sol`
- In `ERC-721.md`, the path to OpenZeppelin’s `SafeERC20.sol` was outdated — their repo structure now has a `/utils/` directory for helpers.
=> Update ERC-3009: fix dead links

ERCS/erc-7743.md, assets/erc-7743/MONFT.sol
This ERC proposes a new standard for non-fungible tokens (NFTs) that supports multiple owners. The MO-NFT standard allows a single NFT to have multiple owners, reflecting the shared and distributable nature of digital assets. This model incorporates mechanisms for provider-defined transfer fees and ownership burning, enabling flexible and collaborative ownership structures. It maintains compatibility with the existing [ERC-721](https://eips.ethereum.org/EIPS/eip-721) standard to ensure interoperability with current tools and platforms.
=> Update ERC-7743: update erc-7743

ERCS/erc-7837.md
This ERC proposes a standard for a new type of fungible token, called Diffusive Tokens (DIFF). Unlike traditional ERC-20 tokens, transferring DIFF tokens does not decrease the sender’s balance. Instead, it mints new tokens directly to the recipient, increasing the total supply on every transfer action. A fixed native currency fee is charged per token transferred, and this fee is paid by the sender to the contract owner. The supply growth is limited by a maximum supply set by the owner. Token holders can also burn their tokens to reduce the total supply. These features enable a controlled, incentivized token distribution model that merges fungibility with a built-in economic mechanism.
=> Update ERC-7837: update author

ERCS/erc-7677.md
Reverts ethereum/ERCs#571 as chain ids are no longer per-call.
=> Update ERC-7677: "Update ERC-7677: chain id update"

ERCS/erc-7847.md
This should clarify how to handle whitespace in the JSON before before taking the sha256 to get the event ID. 
Responding to https://github.com/ethereum/ERCs/pull/782#discussion_r2087677697
=> Update ERC-7847: Clarifying how to handle whitespace for ID calculation

ERCS/erc-7743.md
This ERC proposes a new standard for non-fungible tokens (NFTs) that supports multiple owners. The MO-NFT standard allows a single NFT to have multiple owners, reflecting the shared and distributable nature of digital assets. This model incorporates mechanisms for provider-defined transfer fees and ownership burning, enabling flexible and collaborative ownership structures. It maintains compatibility with the existing [ERC-721](https://eips.ethereum.org/EIPS/eip-721) standard to ensure interoperability with current tools and platforms.
=> Update ERC-7743: Move to Final

ERCS/erc-7412.md, ERCS/erc-7710.md
In response to questions here: https://ethereum-magicians.org/t/towards-more-conversational-wallet-connections-a-proposal-for-the-redeemdelegation-interface/16690/33
=> Update ERC-7710: Improved ERC in response to feedback on ethereum magicians

ERCS/draft-erc-versioned-proxy.md, ERCS/erc-7936.md
This ERC standardizes an interface for proxy contracts that allows callers to explicitly select which version of an implementation contract they want to interact with. Unlike traditional proxy patterns that only expose the latest implementation, this standard enables backward compatibility by maintaining access to previous implementations while supporting upgrades. The versioned proxy maintains a registry of implementation addresses mapped to version identifiers, allowing callers to specify their desired version at call time.
Authors: @Stamp9 @mokita-j @monperrus
=> Add ERC: Versioned Proxy Contract Interface

ERCS/erc-5725.md
Remove duplicate word and fix some typos
=> Update ERC-5725: Remove duplicate word and fix some typos

ERCS/erc-5850.md
=> Update ERC-5850: Fix some typos

ERCS/erc-7682.md
This PR extends `ERC-7682` to specify that when a wallet supports the `auxiliaryFunds` capability, applications using `wallet_sendCalls` must include a `assetsRequiredForExecution` parameter nest under `capabilties` -> `auxiliaryFunds`. This parameter explicitly lists the assets and amounts required for successful execution, as transaction call data alone is insufficient for wallets to infer these requirements.
=> Update ERC-7682: Add section on `capabilities.auxiliaryFunds` parameter, `requiredAssets`

ERCS/erc-7955.md
This PR updates ERC-7955 to propagate CREATE2 reverts as was suggested in the [EIP-7997 discussion](https://ethereum-magicians.org/t/eip-7997-deterministic-factory-predeploy/24998/3).
=> Update ERC-7955: Propagate CREATE2 Reverts

ERCS/erc-7754.md
- **What changed**
- Corrects DKIM reference to [RFC-6376](https://www.rfc-editor.org/rfc/rfc6376.html).
- Updates example manifest URL to `/.well-known/twist.json` and aligns the DNS TXT example.
- Switches example `alg` values to JOSE names (`ES256`, `PS256`) instead of generic labels.
- Adds normative requirements:
- **MUST** support: `ES256`, `EdDSA`.
- **SHOULD** support: `PS256`, `RS256`, `ES384`, `ES512`, `PS384`, `PS512`, `RS384`, `RS512` (per [RFC 7518 §3.1](https://datatracker.ietf.org/doc/html/rfc7518#section-3.1)).
- Specifies public key encoding: X.509 SPKI (DER), represented as hex-encoded strings.
- Recommends using WebCrypto `SubtleCrypto`.
- Improves code sample
=> Update ERC-7754: adding details on 'alg' param
