ethereum/ERCs

ERCS/erc-6357.md
transferring over https://github.com/ethereum/EIPs/pull/7909
=> Update EIP-6357: Move to Last Call

ERCS/erc-7528.md
ported from https://github.com/ethereum/EIPs/pull/7879
=> Update EIP-7528: Move to Review

ERCS/erc-7535.md
ported from https://github.com/ethereum/EIPs/pull/7846
=> ERC-7535: Native Asset ERC-4626 Tokenized Vault

ERCS/erc-7254.md, assets/erc-7254/ERC7254.sol, assets/erc-7254/IERC7254.sol
=> Add ERC-7254

ERCS/erc-7540.md
ported from https://github.com/ethereum/EIPs/pull/7876
=> ERC-7540: Asynchronous ERC-4626 Tokenized Vaults

ERCS/erc-6551.md
=> Update ERC-6551: Registry and execution interface changes

ERCS/erc-5564.md
=> Update ERC-5564: missing necessary arg in computeStealthKey

.github/workflows/post-ci.yml
=> Fix incorrect run summary link

ERCS/erc-5564.md
=> Update ERC-5564: Fix broken links

ERCS/erc-7160.md
=> Update ERC-7160: Move to Last Call

ERCS/erc-7231.md
=> Update ERC-7231: Move to Last Call

ERCS/erc-7535.md
=> Update ERC-7535: Move to Review

ERCS/erc-7439.md
=> Update ERC-7439: Move to Review

config/eip-editors.yml
Add g11tech(myself) to ERC editors
=> Config: Add g11tech to ERC editors

ERCS/erc-7517.md
Fixes links to satisfy htmlproofer
=> Update ERC-7517: Fix links

ERCS/erc-7417.md
=> Update ERC-7417: Update erc-7417.md

ERCS/erc-7066.md
=> Update ERC-7066: Move to Final

ERCS/erc-7439.md
=> Update ERC-7439: Move to Last Call

ERCS/erc-4337.md
=> Update ERC-4337: Fix typos

ERCS/erc-6120.md
Add deployed address, security audit text and and ERC20WithUTR contract sample.
=> Update ERC-6120: update ERC-6120

ERCS/erc-5189.md
Add missing param to isOperationReady
=> Update ERC-5189: Add feeToken to isOperationReady ERC-5189

config/eip-editors.yml
I haven't been active recently. I'd still like to review proposals as they come in, but I haven't been able to meet obligations for governing recently. If I can find the time, I'll request to be added back.
CC @lightclient @axic @gcolvin @SamWilsn @g11tech @xinbenlv
=> Config: Remove myself as governing editor

ERCS/erc-7439.md
=> Update ERC-7439: Move to Final

ERCS/erc-2135.md
=> Update ERC-2135: fix typo

ERCS/erc-7590.md, assets/erc-7590/contracts/IERC7590.sol
=> Update ERC-7590: Improves specification details on ERC7590.

ERCS/erc-7590.md
=> Update ERC-7590: Adds reference to test cases and implementation.

ERCS/erc-1328.md
=> Update ERC-1328: Update erc-1328.md

ERCS/erc-1328.md
=> Update ERC-1328: Move to Last Call

ERCS/erc-5604.md
=> Update ERC-5604: Move to Draft

ERCS/erc-5727.md
=> Update ERC-5727: Improve descriptions

ERCS/erc-7527.md
Changed variable names and deleted redundancy
=> Update ERC-7527: Fix code

ERCS/erc-7231.md
=> Update ERC-7231: Move to Final

ERCS/erc-5585.md
=> Update ERC-5585: Move to Final

ERCS/erc-7531.md
A few people asked me if I was moving to Review because they wanted to implement it in a few projects.
Since there are no recent discussions on Ethereum Magicians and the community looks OK with the proposed interface, I propose advancing it to the Review stage.
=> Update ERC-7531: Move to Review

ERCS/erc-1328.md
deadline passed - can move to final now
=> Update ERC-1328: Move to Final

ERCS/erc-5189.md
`baseFeeScalingFactory` -> `baseFeeScalingFactor`
=> Update ERC-5189: 5189 Spell fix

ERCS/erc-5189.md
- Extend global dependencies to include any global variable that may invalidate an operation
- Specify how to generate the dependency graph within an untrusted environment
=> Update ERC-5189: ERC5189 - Automatic dependency generation

ERCS/erc-7535.md
=> Update ERC-7535: Move to Last Call

ERCS/erc-7627.md, ERCS/erc-76xx.md
=> Add ERC: Secure Messaging Protocol

ERCS/erc-5189.md
- Add `chainId` to operation
- Add operation hash spec
=> Update ERC-5189: 5189 Operation comments

config/eipw.toml
_reported by @pdobacz (hopefully correct username) on discord_
=> Config: Sync with EIPs

ERCS/erc-7627.md
=> Update ERC-7627: To reduce gas costs, the variable type was changed.

ERCS/erc-7627.md
=> Update ERC-7627: Correct some text formatting

ERCS/erc-5189.md
* Update fee logic for low precision tokens
* Add code and slot replacement for accurate simulations
=> Update ERC-5189: ERC-5189 updates

ERCS/erc-7092.md
=> Update ERC-7092: Move to Final

ERCS/erc-7508.md, assets/erc-7508/contracts/AttributesRepository.sol, assets/erc-7508/contracts/IERC7508.sol, assets/erc-7508/contracts/mocks/ERC20Mock.sol, assets/erc-7508/contracts/mocks/OwnableMintableERC721Mock.sol, assets/erc-7508/package.json, assets/erc-7508/test/attributesRepository.ts
Simplifies batch setters and getters.
Refactors code.
Adds methods to set and get attributes metadata URI for collections.
=> Update ERC-7508: Several updates 7508.

ERCS/erc-5173.md
=> Update ERC-5173: Update erc-5173.md

ERCS/erc-7291.md
Added author for the contribution of implementation code
=> Update ERC-7291: Added author

ERCS/erc-7572.md
Reasoning here: https://ethereum-magicians.org/t/erc-7572-contract-level-metadata-via-contracturi/17157/14?u=ryanio
=> Update ERC-7572: remove aspect ratio suggestion from featured_image

ERCS/erc-7631.md
This updates the ERC-7631 proposal with fixes for comments in the interface code samples.
=> Update ERC-7631: Fix interface code comments

ERCS/erc-7573.md
This pull request adds some minor corrections that were left over from https://github.com/ethereum/ERCs/pull/153
=> Update ERC-7573: Feature/erc 7573 finalizing

ERCS/erc-7651.md, ERCS/erc-draft_fractional_nft.md
=> Add ERC: Fractionally Represented Non-Fungible Token

ERCS/erc-7631.md
=> Update ERC-7631: Grammar updates

ERCS/erc-7528.md
=> Update ERC-7528: Move to Final

ERCS/erc-5485.md
=> Update ERC-5485: Move to Draft

ERCS/erc-6900.md
=> Update ERC-6900: Add coauthors from Circle team

config/eipw.toml
Updates ERCs with accordance to EIP-1 update 
https://github.com/ethereum/EIPs/pull/8247
=> Config: add caip

ERCS/erc-6900.md
Adding co-authors from Quantstamp and Alchemy.
=> Update ERC-6900: add co-author names (#8)

ERCS/erc-7562.md
=> Update ERC-7562: Updte ERC-7562 with the latest state from the 'account-abstraction' repo

ERCS/erc-7496.md, assets/erc-7496/DynamicTraitsSchema.json
=> Update ERC-7496: remove acceptableValues (redundant with valueMappings)

ERCS/erc-6672.md
=> Update ERC-6672: Update erc-6672.md

ERCS/erc-6551.md
=> Update ERC-6551: Add hardfork protection to reference implementation

ERCS/erc-7618.md
ERC-7618: Add a clarification suggested by @SamWilsn
=> Update ERC-7618: Add a clarification suggested by @SamWilsn

ERCS/erc-7575.md
=> Update ERC-7575: ERC7575 clarifications

ERCS/erc-6538.md
=> Update ERC-6538: Move to Last Call

ERCS/erc-7540.md
=> Update ERC-7540: ERC7540 rename `requester` => `controller`

ERCS/erc-6551.md
I no longer have access to the previously listed email address. I have updated it to my personal for better long long-term support.
josh@revest.finance ---> jhweintraub@gmail.com
=> Update ERC-6551: Update erc-6551.md

ERCS/erc-7644.md
=> Update ERC-7644: Erc 7644

ERCS/erc-6538.md
=> Update ERC-6538: Move to Final

ERCS/erc-5625.md
=> Update ERC-5625: Move to Review

ERCS/erc-7588.md
=> Update ERC-7588: Move to Review

ERCS/erc-7527.md
=> Update ERC-7527: Update erc-7527.md

ERCS/erc-7615.md
=> Update ERC-7615: Safety update

ERCS/erc-7586.md
=> Update ERC-7586: Move to Review

ERCS/erc-7291.md
=> Update ERC-7291: Update minor text, in preparation for new function parameter updates

ERCS/erc-1078.md, ERCS/erc-1129.md
Hello
I found some spelling issues in your docs.
Hope it helps
Br, Elias.
=> Update ERC-1078: Fix docs

ERCS/erc-7654.md, assets/erc-7654/RequestMethodTypes.sol
=> Update ERC-7654: Add payable for POST and PUT methods

.github/workflows/jekyll-label-bot.yml
=> CI: Update jekyll-label-bot.yml

ERCS/erc-6123.md, assets/erc-6123/contracts/ISDC.sol, assets/erc-6123/contracts/SDCPledgedBalance.sol, assets/erc-6123/test/SDCTests.js
Minor rename of events associated with settlement to better distinguish between trade and settlement.
=> Website: Refactor rename for events associated with settlement.

ERCS/erc-6860.md
ERC-6860: Add the fragment part to the URL definition
=> Update ERC-6860: Add the fragment part to the URL definition.

ERCS/erc-7631.md
Since there has not been changes in API to implementations in the wild for a few months, 
we believe that this ERC is stable, and can be moved to review.
=> Update ERC-7631: Move to Review

ERCS/erc-7677.md
- make paymasterService capability accept a paymasterService object per chain to reflect EIP-5792 update to make calls per-chain
=> Update ERC-7677: chain id update

ERCS/erc-6123.md
Minor fix to headlines (added subsection).
=> Update ERC-6123: Minor fix to headlines (added subsection).

ERCS/erc-7303.md
Remove unnecessary parameters from the sample code.
=> Update ERC-7303: Update erc-7303.md

ERCS/erc-5189.md, ERCS/erc-6900.md
After gathering feedback of a few projects, we are proposing the following adaptations to the ERC-7432 standard.
=> Update ERC-7432: Update Specification

ERCS/erc-7758.md, ERCS/erc-transfer-with-authorization.md
Ref: https://github.com/ethereum/ERCs/pull/504
=> Add ERC: Transfer With Authorization

ERCS/erc-7585.md
=> Update ERC-7585: fix typo

ERCS/erc-7588.md
=> Update ERC-7588: Move to Final

ERCS/erc-7677.md
- moving back to review as 5792 discussions are still ongoing
=> Update ERC-7677: Move to Review

ERCS/erc-7726.md
=> Update ERC-7726: errors are not enforced

ERCS/erc-7758.md
https://ethereum-magicians.org/t/erc-7758-transfer-with-authorization/20859/7
Change status to review
=> Update ERC-7758: Move to Review

ERCS/erc-5791.md
=> Update ERC-5791: update to v2

ERCS/erc-4626.md
a minimal implementation broken link fixed: https://github.com/transmissions11/solmate/blob/main/src/tokens/ERC4626.sol
=> Update ERC-4626: Update erc-4626.md to fix the broken link.

ERCS/erc-7432.md
After a year under discussion, and being adopted by multiple projects, we are ready to move ERC-7432 to Final.
=> Update ERC-7432: Move to Final

ERCS/erc-7751.md, ERCS/erc-draft_wrap_revert.md
=> Add ERC: Wrapping of bubbled up reverts

ERCS/erc-7007.md
Last call deadline passed. Moving to final.
=> Update ERC-7007: Move to Final

.github/workflows/ci.yml, config/eipw.toml
See [`CHANGELOG.md`](https://github.com/ethereum/eipw/blob/master/CHANGELOG.md)
=> CI: Upgrade to eipw 0.9

ERCS/erc-7738.md, assets/erc-7738/contracts/DecentralisedRegistryPermissioned.sol, assets/erc-7738/contracts/IERC7738.sol, assets/erc-7738/hardhat.config.ts, assets/erc-7738/package-lock.json, assets/erc-7738/package.json, assets/erc-7738/scripts/createRegistryEntry.ts, assets/erc-7738/scripts/deploy.ts, assets/erc-7738/scripts/upgradeRegistry.ts, assets/erc-7738/test/DecentralisedRegistry.test.ts, assets/erc-7738/test/PermissionedRegistry.test.ts, assets/erc-7738/tokenscript/onboard.html, assets/erc-7738/tokenscript/out/tokenscript.tsml
This PR updates the ERC-7738 application with clarification on the main spec and fixes issues with attached assets.
=> Website: Clarify spec and fix issues in associated assets

ERCS/erc-7683.md
=> Update ERC-7683: fix typos

ERCS/erc-6123.md, assets/erc-6123/contracts/ERC20Settlement.sol, assets/erc-6123/contracts/ISDC.sol, assets/erc-6123/contracts/SDCSingleTradePledgedBalance.sol, assets/erc-6123/package.json
This PR makes some fixed/changes to the Settlement Token used in the reference implementation of the SDC.
=> Update ERC-6123: Fixes to reference implementation of Settlement Token

ERCS/erc-7699.md
as suggested by Sam during finalization of initial PR #399
=> Update ERC-7699: Update erc-7699.md - suggested minor fixes

ERCS/erc-7496.md
=> Update ERC-7496: Update erc-7496.md - trait metadata as required

ERCS/erc-7743.md, assets/erc-7743/DigitalAsset.sol, assets/erc-7743/IDigitalAsset.sol, assets/erc-7743/MONFT.sol
=> Update ERC-7743: Include Reference Implementation and Finalize MO-NFT Standard

ERCS/erc-7743.md
=> Update ERC-7743: Remove email & format document

ERCS/erc-7722.md
=> Update ERC-7722: added Ante and Mirko as maintainer

ERCS/erc-6900.md
fixes: https://github.com/erc6900/resources/issues/53
also addresses ambiguity around native function addresses
=> Update ERC-6900: IModularAccountView changes

ERCS/eip-1.md, config/eip-editors.yml
Decided in:
- https://github.com/ethcatherders/EIPIP/issues/369
- https://github.com/ethcatherders/EIPIP/issues/368
With @SamWilsn and @lightclient in favour, no one opposing.
=> Move @axic and @gcolvin to emeritus.

ERCS/erc-6900.md
=> Update ERC-6900: Clean up comments

ERCS/erc-5625.md
=> Update ERC-5625: Move to Final

ERCS/erc-7722.md
Described ERC-7722 events and user roles
=> Update ERC-7722: describe events and roles

ERCS/erc-1078.md
=> Update ERC-1078: Typo ERC-1078

ERCS/erc-7562.md
=> Update ERC-7562: Update ERC-7562 rules to add EIP-7702 authorizations support

ERCS/erc-7786.md
=> Update ERC-7786: ERC-7786 update

ERCS/erc-7821.md
=> Update ERC-7821: Add comment on allowing entry point for execute

ERCS/erc-7746.md
=> Update ERC-7746: Move to Review

ERCS/erc-7820.md
=> Update ERC-7820: Move to Review

ERCS/erc-7734.md
=> Update ERC-7734: Move to Review

ERCS/erc-7555.md
fix a typo: wesbite -> website
=> Update ERC-7555: fix typo

ERCS/erc-7656.md
This change improves the security considerations adding more cases that should be considered by developers, users, and marketplaces.
=> Update ERC-7656: Improve security considerations

ERCS/erc-7527.md
Update erc-7527.md 
Agency's description() function
from `function description() public view returns (string);` to `function description() external view returns (string memory);`
=> Update ERC-7527: Update erc-7527.md Agency's description() function

ERCS/erc-7751.md
=> Update ERC-7751: Move to Last Call

ERCS/erc-7734.md
=> Update ERC-7734: Move to Last Call

ERCS/erc-7777.md
=> Update ERC-7777: Move to Review

ERCS/erc-7562.md
=> Update ERC-7562: replace by fee reputation.

ERCS/erc-7821.md
=> Update ERC-7821: Fix incorrect code comment

ERCS/erc-7562.md
=> Update ERC-7562: Update erc-7562.md

ERCS/erc-7015.md
fix a typo: singature -> signature
=> Update ERC-7015: fix typo

ERCS/erc-7734.md
=> Update ERC-7734: Move to Final

ERCS/erc-7820.md
=> Update ERC-7820: Move to Final

ERCS/erc-7821.md
=> Update ERC-7821: Add batch of batches mode

ERCS/erc-7656.md
=> Update ERC7656: Minor text changes before finalizing

ERCS/erc-7796.md
=> Update ERC-7796: The correct EIP-7702 code prefix is '0xef0100' not '0xef01'

ERCS/erc-4337.md
=> Update ERC-4337: Add the 'receive()' function to the public interface

ERCS/erc-4337.md
=> Update ERC-4337: Replace references to EIP-3074 with EIP-7702

ERCS/erc-4337.md
=> Update ERC-4337: Add link to ERC-7796 'eth_sendRawTransactionConditional'

ERCS/erc-7562.md
=> Update ERC-7562: Updated erc 7562

ERCS/erc-7769.md
=> Update ERC-7769: Elaborate how EIP-7702 support works

ERCS/erc-7769.md
=> Update ERC-7769: Rephrase one sentence

ERCS/erc-7562.md
=> Update ERC-7562: Fixing phases description

ERCS/erc-7562.md
=> Update ERC-7562: InclusionRate definition fix

ERCS/erc-7562.md
=> Update ERC-7562: Removing "accountable" from definition

ERCS/erc-4337.md
=> Update ERC-4337: Add mention of PER_EMPTY_ACCOUNT_COST

ERCS/erc-4337.md
=> Update ERC-4337: Fixes audit 2

ERCS/erc-4337.md
=> Update ERC-4337: Adding use cases to motivation

ERCS/erc-7562.md
=> Update ERC-7562: Unstaked paymaster context

assets/erc-4519/PoC_SmartNFT/PoC_SmartNFT.sol
khow - know 
I hope my correction will contribute to the project's development. Thank you for the time you gave me.
=> Refined text by fixing typos and improving clarity

assets/erc-5773/contracts/library/MultiAssetLib.sol, assets/erc-6123/contracts/ERC20Settlement.sol
**reasource - resource**
**perfoms - performs**
=> chore: docs fix spelling issues 

ERCS/erc-6105.md
=> Update ERC-6105: Remove redundant word

assets/erc-5252/test/Lock.ts
corrected:
snapshopt - snapshot
=> fixed typos

ERCS/erc-7897.md
I am withdrawing this proposal because the same result can be achieved with ERC-7656.
=> Update ERC-7897: Move to Withdrawn

ERCS/erc-7656.md
=> Update ERC-7656: Fix interface id

ERCS/erc-7821.md
=> Update ERC-7821: Rename target -> to

ERCS/erc-7913.md
=> Update ERC-7913: Update erc-7913.md

ERCS/erc-7913.md
=> Update ERC-7913: Add security considerations

ERCS/erc-7802.md
This PR addresses feedback provided on #692 . In particular, the following review: https://github.com/ethereum/ERCs/pull/692#issuecomment-2539820177
It also includes a new section in Security Considerations that discusses Wrapped Native Tokens.
=> Update ERC-7802: Address feedback and include Native Token Security Considerations

ERCS/erc-7744.md, assets/erc-7744/ERC7744.sol, assets/erc-7744/IERC7744.sol
- Renamed assets in directory to have corresponding names.
- Added latest 7702 changes to delegated EOA contract detection.
- Added more explicit compilation instructions to ensure nothing is hidden in my sleeve.
=> Update ERC-7744: updated erc7744 with latest 7702 changes, renamed assets with standard number

assets/erc-5218/contracts/README.md
=> fix dead link `Foundry ` README.md

ERCS/erc-7878.md
As explained in the Ethereum EIP Editing Office Hour Meeting 57, this EIP is already being used by ScanSan Properties and we think it is ready for review. 
@ethereum/eip-editors, please consider moving it to 'Review' status.
=> Update ERC-7878: Move to Review

assets/erc-7401/contracts/NestableToken.sol, assets/erc-7401/test/nestable.ts
=> Update ERC-7401: Fix some typos

ERCS/erc-7812.md
=> Update ERC-7812: Update ERC-7812 addresses

ERCS/erc-7291.md
=> Update ERC-7291: Move to Last Call

ERCS/erc-6909.md
=> Update ERC-6909: update username jtriley-eth -> jtriley2p

ERCS/erc-6358.md
This PR focuses on correcting typos and improving clarity in documentation files.
Thank you very much.
=> Update ERC-6358: fix typos

ERCS/erc-7597.md
=> Update ERC-7597: Remove redundant word

ERCS/erc-7399.md
=> Update ERC-7399: Move to Review

ERCS/erc-7813.md
This EIP is already being used by MUD projects in production, and we believe it is ready to be moved to Review.
=> Update ERC-7813: Move to Review

ERCS/erc-7739.md
=> Update ERC-7739: Remove redundant word

ERCS/erc-5516.md
hey team! I found duplicate words and fixed them.
=> Update ERC-5516: fix duplicate `and and` erc-5516.md

ERCS/erc-7947.md, ERCS/erc-xxxx.md
A quick one. Would love to hear your thoughts about this!
=> Add ERC: Account Abstraction Recovery Interface

ERCS/erc-7964.md, ERCS/erc-xxxx.md
=> Add ERC: Cross-Chain EIP-712 Signing Domains

ERCS/erc-7812.md
Would like to move the ERC to the review stage.
=> Update ERC-7812: Move to Review

ERCS/erc-6224.md
The ERC has been "in review" for quite a while now, would like to move it to the next stage.
=> Update ERC-6224: Move to Last Call

ERCS/erc-7631.md
=> Update ERC-7631: Move to Final

ERCS/erc-7744.md
=> Update ERC-7744: Move to Last Call

assets/erc-7765/contracts/ERC7765Example.sol
=> Update ERC-7765: Fix some typos

assets/erc-6358/src/contracts/ERC6358FungibleExample.sol, assets/erc-6358/src/contracts/ERC6358NonFungibleExample.sol, assets/erc-6358/src/contracts/interfaces/IERC6358.sol, assets/erc-6358/src/contracts/interfaces/IERC6358Application.sol, assets/erc-6358/src/contracts/libraries/OmniverseProtocolHelper.sol
=> Update ERC-6358: Fix some typos

ERCS/erc-7858.md
Include a use case in the motivation section and highlight new security considerations.
=> Update ERC-7858: Add use case in motivation and point new security considerations

ERCS/erc-7780.md
=> Update ERC-7780: Fix some typos

ERCS/erc-7878.md
We feel the ERC is ready for the Last Call
=> Update ERC-7878: Move to Last Call

ERCS/erc-7913.md
Follow up to https://github.com/ethereum/ERCs/pull/1124#discussion_r2240361851
=> Update ERC-7913: Update last-call-deadline

ERCS/erc-7943.md
Based on the discussion from here: https://ethereum-magicians.org/t/erc-7943-universal-rwa-interface-urwa/23972/68?u=mihaic195
cc @xaler5
=> Update ERC-7943: Make tokenId indexed for ForcedTransfer event

ERCS/erc-7654.md, assets/erc-7654/RequestMethodTypes.sol
This is a method description. It can be used as a prompt in AI applications. This indicates that erc7654 can be used as a tool function by AI agents.
=> Update ERC-7654: Added instruction to erc7654

ERCS/erc-7878.md
Transitioned to Final status, 2025-09-03
=> Update ERC-7878: Move to Final

ERCS/erc-7943.md
=> Update ERC-7943: small formatting

ERCS/erc-7291.md
=> Update ERC-7291: Move to Final

ERCS/erc-7950.md
=> Update ERC-7950: Move to Final

ERCS/erc-7730.md
- Expand abstract to include machine-interpretable use cases (e.g., transaction simulation)
- Clarify motivation to emphasize both human UX and automated system benefits
- Update terminology: "dApps" → "app" for broader applicability
- Add EIP-5792 (batch transactions) to future extensibility
- Strengthen security considerations:
- Highlight phishing attack vectors (parameter injection, registry poisoning, front-end compromise)
- Emphasize cryptographic binding requirements
- Add detailed registry security recommendations (provenance, tamper-evident history, governance)
- Replace deployment model section with registry poisoning mitigation guidance
- Note future work on frontend-to-contract binding
- Add Derek Rein as co-author
When opening a pull request to submit a new EIP, please use …
=> Update ERC-7730: Expand scope to machine consumption, enhance security considerations
